language: python

branches:
  except:
    - gh-pages

cache:
  directories:
    - "${HOME}/.pip"

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.5
      env: TOXENV=py35
    - python: 3.4
      env: TOXENV=py34
    - python: 3.3
      env: TOXENV=py33
    - python: 2.7
      env: TOXENV=py27
    - python: pypy
      env: TOXENV=pypy
  allow_failures:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.4
      env: TOXENV=py34
    - python: 3.3
      env: TOXENV=py33

install:
  - pip install tox

script:
  - tox -- --ignore=tests/integration
  - "find ${TRAVIS_BUILD_DIR}/.tox -name log -type d | xargs -I {} rm -rf {}"

after_success:
  - pip install coveralls
  - coveralls

notifications:
  slack: storjcommunity:TZfUO9ycY8R9UYwztWZTo0jk
  email: false

deploy:
  provider: pypi
  user: super3
  password:
    secure: secret
  on:
    tags: true

